/*
 * Sakila Database Business Intelligence Queries
 * Advanced SQL queries for business insights and analytics
 * Database: sakila (MySQL sample database for DVD rental business)
 * 
 * These queries demonstrate:
 * - Complex joins
 * - Subqueries and CTEs (Common Table Expressions)
 * - Aggregate functions with GROUP BY
 * - Window functions concepts
 * - Business metrics calculations
 */

-- ============================================
-- 1. TOP 5 MOST ACTIVE CUSTOMERS (BY RENTAL COUNT)
-- Business Use: Identify loyal customers for rewards programs
-- ============================================

SELECT
    C.customer_id,
    C.first_name,
    C.last_name,
    COUNT(R.rental_id) AS total_rentals
FROM
    customer C
JOIN
    rental R ON C.customer_id = R.customer_id
GROUP BY
    C.customer_id, C.first_name, C.last_name
ORDER BY
    total_rentals DESC
LIMIT 5;


-- ============================================
-- 2. TOTAL REVENUE GENERATED BY EACH STORE
-- Business Use: Compare store performance and profitability
-- ============================================

SELECT
    S.store_id,
    SUM(P.amount) AS total_store_revenue
FROM
    store S
JOIN
    staff ST ON S.store_id = ST.store_id
JOIN
    payment P ON ST.staff_id = P.staff_id
GROUP BY
    S.store_id
ORDER BY
    total_store_revenue DESC;


-- ============================================
-- 3. FILMS THAT HAVE NEVER BEEN RENTED
-- Business Use: Identify underperforming inventory for potential removal
-- ============================================

SELECT
    F.title AS unrented_film_title
FROM
    film F
LEFT JOIN
    inventory I ON F.film_id = I.film_id
LEFT JOIN
    rental R ON I.inventory_id = R.inventory_id
WHERE
    R.rental_id IS NULL  -- A rental entry does not exist for this film copy
GROUP BY
    F.title
ORDER BY
    F.title;


-- ============================================
-- 4. AVERAGE RENTAL DURATION (IN DAYS) PER FILM RATING
-- Business Use: Understand customer viewing patterns by content rating
-- ============================================

SELECT
    F.rating,
    AVG(DATEDIFF(R.return_date, R.rental_date)) AS avg_rental_duration_days
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
GROUP BY
    F.rating
ORDER BY
    avg_rental_duration_days DESC;


-- ============================================
-- 5. ACTIVE CUSTOMER COUNT BY CITY AND COUNTRY
-- Business Use: Geographic analysis for expansion or marketing strategies
-- ============================================

SELECT
    CI.city AS customer_city,
    CO.country AS customer_country,
    COUNT(C.customer_id) AS active_customer_count
FROM
    customer C
JOIN
    address A ON C.address_id = A.address_id
JOIN
    city CI ON A.city_id = CI.city_id
JOIN
    country CO ON CI.country_id = CO.country_id
WHERE
    C.active = 1
GROUP BY
    CI.city, CO.country
ORDER BY
    active_customer_count DESC
LIMIT 10;


-- ============================================
-- 6. TOP 3 REVENUE-GENERATING FILM CATEGORIES
-- Business Use: Focus inventory purchases on profitable genres
-- ============================================

SELECT
    CAT.name AS category_name,
    SUM(P.amount) AS category_revenue
FROM
    category CAT
JOIN
    film_category FC ON CAT.category_id = FC.category_id
JOIN
    inventory I ON FC.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
JOIN
    payment P ON R.rental_id = P.rental_id
GROUP BY
    CAT.name
ORDER BY
    category_revenue DESC
LIMIT 3;


-- ============================================
-- 7. FILMS WITH RENTAL RATE ABOVE AVERAGE
-- Business Use: Identify premium-priced films for targeted promotions
-- ============================================

SELECT
    title,
    rental_rate
FROM
    film
WHERE
    rental_rate > (
        SELECT AVG(rental_rate)
        FROM film
    )
ORDER BY
    rental_rate DESC;


-- ============================================
-- 8. STAFF PERFORMANCE BY AVERAGE TRANSACTION AMOUNT
-- Business Use: Evaluate staff effectiveness and training needs
-- ============================================

SELECT
    ST.first_name,
    ST.last_name,
    ST.staff_id,
    AVG(P.amount) AS average_payment_amount
FROM
    staff ST
JOIN
    payment P ON ST.staff_id = P.staff_id
GROUP BY
    ST.staff_id, ST.first_name, ST.last_name
ORDER BY
    average_payment_amount DESC;


-- ============================================
-- 9. FILMS RENTED EXACTLY ONCE (NICHE CONTENT)
-- Business Use: Identify niche films with limited appeal
-- ============================================

SELECT
    F.title,
    COUNT(R.rental_id) AS rental_count
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
GROUP BY
    F.title
HAVING
    rental_count = 1
ORDER BY
    F.title;


-- ============================================
-- 10. INVENTORY DISTRIBUTION ACROSS STORES
-- Business Use: Ensure balanced inventory allocation between locations
-- Uses: CTE (Common Table Expression) for improved readability
-- ============================================

SELECT
    S.store_id,
    COUNT(I.inventory_id) AS store_inventory_count,
    ROUND( (COUNT(I.inventory_id) * 100.0) / SUM(COUNT(I.inventory_id)) OVER(), 2) AS percentage_of_total_inventory
FROM
    store S
JOIN
    inventory I ON S.store_id = I.store_id
GROUP BY
    S.store_id
ORDER BY
    store_inventory_count DESC;


-- ============================================
-- 11. HIGH-VALUE CUSTOMERS ABOVE AVERAGE SPENDING
-- Business Use: Identify premium customers for VIP programs
-- Uses: CTE for calculating average spending baseline
-- ============================================

WITH CustomerTotalSpending AS (
    SELECT
        customer_id,
        SUM(amount) AS total_spent
    FROM
        payment
    GROUP BY
        customer_id
),
OverallAverage AS (
    SELECT AVG(total_spent) AS average_spending
    FROM CustomerTotalSpending
)
SELECT
    C.first_name,
    C.last_name,
    CTS.total_spent
FROM
    customer C
JOIN
    CustomerTotalSpending CTS ON C.customer_id = CTS.customer_id
CROSS JOIN
    OverallAverage OA
WHERE
    CTS.total_spent > OA.average_spending
ORDER BY
    CTS.total_spent DESC;


-- ============================================
-- 12. FILM WITH LONGEST AVERAGE RENTAL PERIOD
-- Business Use: Identify highly engaging content that customers keep longer
-- ============================================

SELECT
    F.title,
    AVG(DATEDIFF(R.return_date, R.rental_date)) AS avg_rental_days
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
WHERE
    R.return_date IS NOT NULL
GROUP BY
    F.title
ORDER BY
    avg_rental_days DESC
LIMIT 1;


-- ============================================
-- 13. TOP 5 CUSTOMERS BY LIFETIME SPENDING
-- Business Use: Recognize top spenders and their preferred store locations
-- ============================================

SELECT
    C.first_name,
    C.last_name,
    S.store_id AS assigned_store_id,
    SUM(P.amount) AS lifetime_spending
FROM
    customer C
JOIN
    payment P ON C.customer_id = P.customer_id
JOIN
    store S ON C.store_id = S.store_id
GROUP BY
    C.customer_id, C.first_name, C.last_name, S.store_id
ORDER BY
    lifetime_spending DESC
LIMIT 5;


-- ============================================
-- 14. REPLACEMENT COST ANALYSIS BY RATING
-- Business Use: Understand inventory investment risk by content rating
-- ============================================

SELECT
    rating,
    MAX(replacement_cost) AS max_cost,
    MIN(replacement_cost) AS min_cost,
    (MAX(replacement_cost) - MIN(replacement_cost)) AS cost_range
FROM
    film
GROUP BY
    rating
ORDER BY
    cost_range DESC;


-- ============================================
-- 15. STORE MANAGERS AND ACTIVE CUSTOMER BASE
-- Business Use: Evaluate manager performance based on customer retention
-- Uses: CTE for customer aggregation
-- ============================================

WITH ActiveCustomersPerStore AS (
    SELECT
        store_id,
        COUNT(customer_id) AS active_customer_count
    FROM
        customer
    WHERE
        active = 1
    GROUP BY
        store_id
)
SELECT
    M.first_name AS manager_first_name,
    M.last_name AS manager_last_name,
    S.store_id,
    ACPS.active_customer_count
FROM
    store S
JOIN
    staff M ON S.manager_staff_id = M.staff_id
JOIN
    ActiveCustomersPerStore ACPS ON S.store_id = ACPS.store_id
ORDER BY
    ACPS.active_customer_count DESC;