-- 1. TOP 5 MOST ACTIVE CUSTOMERS (BY RENTAL COUNT)

SELECT
    C.customer_id,
    C.first_name,
    C.last_name,
    COUNT(R.rental_id) AS total_rentals
FROM
    customer C
JOIN
    rental R ON C.customer_id = R.customer_id
GROUP BY
    C.customer_id, C.first_name, C.last_name
ORDER BY
    total_rentals DESC
LIMIT 5;


-- 2. TOTAL REVENUE GENERATED BY EACH STORE

SELECT
    S.store_id,
    SUM(P.amount) AS total_store_revenue
FROM
    store S
JOIN
    staff ST ON S.store_id = ST.store_id
JOIN
    payment P ON ST.staff_id = P.staff_id
GROUP BY
    S.store_id
ORDER BY
    total_store_revenue DESC;


-- 3. FILMS THAT HAVE NEVER BEEN RENTED (Potential Inventory Decommissioning)

SELECT
    F.title AS unrented_film_title
FROM
    film F
LEFT JOIN
    inventory I ON F.film_id = I.film_id
LEFT JOIN
    rental R ON I.inventory_id = R.inventory_id
WHERE
    R.rental_id IS NULL  -- A rental entry does not exist for this film copy
GROUP BY
    F.title
ORDER BY
    F.title;


-- 4. AVERAGE RENTAL DURATION (IN DAYS) PER FILM RATING

SELECT
    F.rating,
    AVG(DATEDIFF(R.return_date, R.rental_date)) AS avg_rental_duration_days
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
GROUP BY
    F.rating
ORDER BY
    avg_rental_duration_days DESC;


-- 5. ACTIVE CUSTOMER COUNT BY CITY AND COUNTRY

SELECT
    CI.city AS customer_city,
    CO.country AS customer_country,
    COUNT(C.customer_id) AS active_customer_count
FROM
    customer C
JOIN
    address A ON C.address_id = A.address_id
JOIN
    city CI ON A.city_id = CI.city_id
JOIN
    country CO ON CI.country_id = CO.country_id
WHERE
    C.active = 1
GROUP BY
    CI.city, CO.country
ORDER BY
    active_customer_count DESC
LIMIT 10;


-- 6. TOP 3 REVENUE-GENERATING FILM CATEGORIES

SELECT
    CAT.name AS category_name,
    SUM(P.amount) AS category_revenue
FROM
    category CAT
JOIN
    film_category FC ON CAT.category_id = FC.category_id
JOIN
    inventory I ON FC.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
JOIN
    payment P ON R.rental_id = P.rental_id
GROUP BY
    CAT.name
ORDER BY
    category_revenue DESC
LIMIT 3;


-- 7. FILMS WITH RENTAL RATE ABOVE THE OVERALL DATABASE AVERAGE

SELECT
    title,
    rental_rate
FROM
    film
WHERE
    rental_rate > (
        SELECT AVG(rental_rate)
        FROM film
    )
ORDER BY
    rental_rate DESC;


-- 8. STAFF PERFORMANCE BY AVERAGE TRANSACTION AMOUNT

SELECT
    ST.first_name,
    ST.last_name,
    ST.staff_id,
    AVG(P.amount) AS average_payment_amount
FROM
    staff ST
JOIN
    payment P ON ST.staff_id = P.staff_id
GROUP BY
    ST.staff_id, ST.first_name, ST.last_name
ORDER BY
    average_payment_amount DESC;


-- 9. FILMS RENTED EXACTLY ONCE (HIGHLY NICHE)

SELECT
    F.title,
    COUNT(R.rental_id) AS rental_count
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
GROUP BY
    F.title
HAVING
    rental_count = 1
ORDER BY
    F.title;


-- 10. PERCENTAGE OF TOTAL INVENTORY HELD AT EACH STORE (Using CTE for clarity)

WITH TotalInventory AS (
    SELECT COUNT(*) AS total_count
    FROM inventory
)
SELECT
    S.store_id,
    COUNT(I.inventory_id) AS store_inventory_count,
    ROUND( (COUNT(I.inventory_id) * 100.0) / TI.total_count, 2) AS percentage_of_total_inventory
FROM
    store S
JOIN
    inventory I ON S.store_id = I.store_id
CROSS JOIN
    TotalInventory TI
GROUP BY
    S.store_id, TI.total_count
ORDER BY
    store_inventory_count DESC;


-- 11. CUSTOMERS WHO SPENT MORE THAN THE AVERAGE LIFETIME SPENDING (Using CTE for clarity)

WITH CustomerTotalSpending AS (
    SELECT
        customer_id,
        SUM(amount) AS total_spent
    FROM
        payment
    GROUP BY
        customer_id
),
OverallAverage AS (
    SELECT AVG(total_spent) AS average_spending
    FROM CustomerTotalSpending
)
SELECT
    C.first_name,
    C.last_name,
    CTS.total_spent
FROM
    customer C
JOIN
    CustomerTotalSpending CTS ON C.customer_id = CTS.customer_id
CROSS JOIN
    OverallAverage OA
WHERE
    CTS.total_spent > OA.average_spending
ORDER BY
    CTS.total_spent DESC;


-- 12. FILM TITLE WITH THE LONGEST AVERAGE RENTAL PERIOD

SELECT
    F.title,
    AVG(DATEDIFF(R.return_date, R.rental_date)) AS avg_rental_days
FROM
    film F
JOIN
    inventory I ON F.film_id = I.film_id
JOIN
    rental R ON I.inventory_id = R.inventory_id
WHERE
    R.return_date IS NOT NULL
GROUP BY
    F.title
ORDER BY
    avg_rental_days DESC
LIMIT 1;


-- 13. TOP 5 CUSTOMERS BY LIFETIME SPENDING AND THEIR ASSOCIATED STORE LOCATION

SELECT
    C.first_name,
    C.last_name,
    S.store_id AS assigned_store_id,
    SUM(P.amount) AS lifetime_spending
FROM
    customer C
JOIN
    payment P ON C.customer_id = P.customer_id
JOIN
    store S ON C.store_id = S.store_id
GROUP BY
    C.customer_id, C.first_name, C.last_name, S.store_id
ORDER BY
    lifetime_spending DESC
LIMIT 5;


-- 14. REPLACEMENT COST VOLATILITY (RANGE) PER RATING CATEGORY

SELECT
    rating,
    MAX(replacement_cost) AS max_cost,
    MIN(replacement_cost) AS min_cost,
    (MAX(replacement_cost) - MIN(replacement_cost)) AS cost_range
FROM
    film
GROUP BY
    rating
ORDER BY
    cost_range DESC;


-- 15. MANAGERS AND THE NUMBER OF ACTIVE CUSTOMERS ASSIGNED TO THEIR STORE (Using CTE for clarity)

WITH ActiveCustomersPerStore AS (
    SELECT
        store_id,
        COUNT(customer_id) AS active_customer_count
    FROM
        customer
    WHERE
        active = 1
    GROUP BY
        store_id
)
SELECT
    M.first_name AS manager_first_name,
    M.last_name AS manager_last_name,
    S.store_id,
    ACPS.active_customer_count
FROM
    store S
JOIN
    staff M ON S.manager_staff_id = M.staff_id
JOIN
    ActiveCustomersPerStore ACPS ON S.store_id = ACPS.store_id
ORDER BY
    ACPS.active_customer_count DESC;